version: "3.9"

services:
  backend:
    build:
      context: ./BE-Music-Downloader/
      dockerfile: Dockerfile.backend
    image: ${DOCKER_USERNAME}/music-downloader:latest
    container_name: music-downloader
    volumes:
      - storage_for_songs:/app/music
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
  
  frontend:
    build:
      context: ./FE-Music-Downloader/
      dockerfile: Dockerfile.frontend
    image: ${DOCKER_USERNAME}/music-downloader-frontend:latest
    container_name: music-downloader-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  storage_for_songs: