FROM node:22.4.0-alpine
# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json .

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 5173

WORKDIR /app/FE-Music-Downloader

CMD ["npm", "run", "dev"]